#profile= development

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/webflux-gateway
    username: postgres
    password: postgres
  ## PostgreSQL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults : false

logging:
  level:
    com.ard333.springbootwebfluxjjwt: debug
    org.springframework.*: debug